[package]
name = "roku_control"
version = "0.1.0"
edition = "2021"

[dependencies]
argparse = {version = "0.2.2"}
reqwest ={ version = "0.12.3"}
tokio ={ version = "1.37.0", features = ["full"]}
colorized ={ version = "1.0.0"}